"use client";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/globals.css";
import { PropsWithChildren } from "react";
import StoreProvider from "@/redux/storeProvider";
import { CssBaseline, StyledEngineProvider, ThemeProvider, createTheme, Box } from "@mui/material";
import { ToastContainer } from "react-toastify";

const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  palette: {
    mode: 'light',
  },
  typography: {
    fontFamily: montserrat.style.fontFamily,
  },
});

export default function RootLayout({ children, ...props }: PropsWithChildren) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      />
      <body
        style={{ width: "100vw", height: "100vh", margin: 0, padding: 0, right: 0, left: 0, display: "block" }}
        className={`${montserrat.className}`}
      >
        <StyledEngineProvider injectFirst>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <StoreProvider>
              <Box>
                {children},
                <ToastContainer />
              </Box>
            </StoreProvider>
          </ThemeProvider>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
